import { OBXRow } from "..";

export const referenceRanges = {
  WBC: { min: 4.0, max: 10.0 },
  "LYM%": { min: 20.0, max: 40.0 },
  "MID%": { min: 3.0, max: 15.0 },
  "GRAN%": { min: 50.0, max: 70.0 },
  HGB: { min: 110.0, max: 160.0 },
  RBC: { min: 3.5, max: 5.5 },
  HCT: { min: 37.0, max: 54.0 },
  MCV: { min: 80.0, max: 100.0 },
  MCH: { min: 27.0, max: 34.0 },
  MCHC: { min: 320.0, max: 360.0 },
  PLT: { min: 150.0, max: 400.0 },
};

export const bloodTestTemplates: OBXRow[] = [
  {
    id: "1",
    testName: "White Blood Cells",
    testCode: "WBC",
    testValue: 0,
    referenceRange: "4.0-10.0",
    unit: "10^3/uL",
    status: "Normal",
  },
  {
    id: "2",
    testName: "Lymphocytes %",
    testCode: "LYM%",
    testValue: 0,
    referenceRange: "20.0-40.0",
    unit: "%",
    status: "Normal",
  },
  {
    id: "3",
    testName: "Monocytes %",
    testCode: "MID%",
    testValue: 0,
    referenceRange: "3.0-15.0",
    unit: "%",
    status: "Normal",
  },
  {
    id: "4",
    testName: "Granulocytes %",
    testCode: "GRAN%",
    testValue: 0,
    referenceRange: "50.0-70.0",
    unit: "%",
    status: "Normal",
  },
  {
    id: "5",
    testName: "Hemoglobin",
    testCode: "HGB",
    testValue: 0,
    referenceRange: "110.0-160.0",
    unit: "g/dL",
    status: "Normal",
  },
  {
    id: "6",
    testName: "Red Blood Cells",
    testCode: "RBC",
    testValue: 0,
    referenceRange: "3.5-5.5",
    unit: "10^6/uL",
    status: "Normal",
  },
  {
    id: "7",
    testName: "Hematocrit",
    testCode: "HCT",
    testValue: 0,
    referenceRange: "37.0-54.0",
    unit: "%",
    status: "Normal",
  },
  {
    id: "8",
    testName: "Mean Corpuscular Volume",
    testCode: "MCV",
    testValue: 0,
    referenceRange: "80.0-100.0",
    unit: "fL",
    status: "Normal",
  },
  {
    id: "9",
    testName: "Mean Corpuscular Hemoglobin",
    testCode: "MCH",
    testValue: 0,
    referenceRange: "27.0-34.0",
    unit: "pg",
    status: "Normal",
  },
  {
    id: "10",
    testName: "Mean Corpuscular Hemoglobin Concentration",
    testCode: "MCHC",
    testValue: 0,
    referenceRange: "320.0-360.0",
    unit: "g/L",
    status: "Normal",
  },
  {
    id: "11",
    testName: "Platelets",
    testCode: "PLT",
    testValue: 0,
    referenceRange: "150.0-400.0",
    unit: "10^9/L",
    status: "Normal",
  },
];
